apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {cluster-issuer-name}
spec:
  acme:
    server: {serverurl}
    email: {myemailid}
    privateKeySecretRef:
      name: {cluster-issuer-name}
    http01: {}
